### ISSUE TITLE
Legends

### ISSUE THREAD

**Issue by naitian** [MichiganDaily/bore#4]
**Is your feature request related to a problem? Please describe.**
Add support for including legends.

**Describe the solution you'd like**
Could potentially be implemented as a mixin? Still unsure.

**Comment by naitian** [comment]
Going to close this issue for now, because I don't think this is going to generalize with our new approach to charts.

**Comment by erxclau** [comment]
Maybe something like

```javascript
svg.call(
    bore.build(
        new bore.Visual()
            .legend(
                new bore.LegendType()
            )
    )
)
```
